# SITE CONFIGURATION
baseurl: "/algoguru"
url: "https://coolwindjo.github.io"
title: Cool Wind

# THEME-SPECIFIC CONFIGURATION
title: Cool wind on prob_solv # blog's title
description: "Blog posts and pages with cool wind" # used by search engines
avatar: assets/img/cls.png
favicon: assets/img/cls.png 
gravatar: # Email MD5 hash

# Header and footer text
header_text: Cool wind on studying algorithm <code>prob_solv</code>
header_feature_image: assets/img/pexels/cls63amg_running.jpeg
footer_text: >
  © 2019 coolwind@outlook.kr All rights reserved. Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for social icons, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
disqus_shortname:                                       # Your discus shortname for comments

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
